name: celest_backend
description: The Celest backend for trivia_backend.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  celest: ^1.0.0
  celest_core: ^1.0.0
  drift: ^2.20.2
  drift_hrana: ^1.0.2
  get_it: ^7.7.0
  meta: ^1.12.0
  retry: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.19.1
  lints: ^4.0.0
  test: ^1.25.0
celest:
  project:
    id: project_01j6wwyexcfpbxenzypygakgyk

dependency_overrides:
  web: '>=0.5.0 <2.0.0'